[devices]

    [devices.printer]
        name = "Winbond Electronics Corp. Virtual Com Port"
        vendor_id = "0x0416"
        product_id = "0x5011"
        paper_width = "80mm"
        has_cutter = true

    [devices.camera]
        name = "Cheng Uei Precision Industry Co., Ltd (Foxlink) FH13FF-238"
        vendor_id = "0x05c8"
        product_id = "0x030e"
        device = "/dev/video-webcam"
